// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://assllfqtawetmooxeglu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzc2xsZnF0YXdldG1vb3hlZ2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Njk0NTgsImV4cCI6MjA2MDE0NTQ1OH0.2kmql7RqIoRwQzYORZbHElUlctbeSQLuQcMgHShVyt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);