// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmtoewxdtrppzohanym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbXRvZXd4ZHRycHB6b2hhbnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjU0NjIsImV4cCI6MjA1NzMwMTQ2Mn0.knz4224Xhstz1UmZscqrNiwFd_TcaL9hB84___aHtcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);